
spring:
  security:
    user:
      name: fmartinezvidal
      password: 2908
  datasource:
    url: jdbc:postgres://localhost:5432/springbank
    username: fmartinezvidal
    password: 2908
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.api: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"